version: "3.7"
services:
  php:
    container_name: "mautic"
    build: .
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./.docker/apache/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - .:/var/www/html
    ports:
      - 80:80
      - 443:443
    networks:
      - mynetwork

  mysql:
    image: mysql:5.7.26
    container_name: "mysql"
    volumes:
      - .docker/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mautic
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD:
      MYSQL_USER: mautic
      MYSQL_PASSWORD: 123
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
