<?php
$parameters = array(
	'db_driver' => 'pdo_mysql',
	'db_host' => 'mysql',
	'db_table_prefix' => null,
	'db_port' => '3306',
	'db_name' => 'mautic',
	'db_user' => 'mautic',
	'db_password' => '123',
	'db_backup_tables' => 1,
	'db_backup_prefix' => 'bak_',
	'mailer_from_name' => 'Jon Batista',
	'mailer_from_email' => 'batista.jonathas@gmail.com',
	'mailer_transport' => 'mautic.transport.amazon',
	'mailer_host' => null,
	'mailer_port' => null,
	'mailer_user' => 'AKIA5ICRZI4J6IFB2IWE',
	'mailer_password' => 'BFZMe0gyrTgT+ruempBzQlA3RLe5TNpPKRlUiCm/bXfp',
	'mailer_amazon_region' => 'us-east-1',
	'mailer_amazon_other_region' => null,
	'mailer_api_key' => null,
	'mailer_encryption' => null,
	'mailer_auth_mode' => null,
	'mailer_spool_type' => 'memory',
	'mailer_spool_path' => '%kernel.root_dir%/../var/spool',
	'secret_key' => '6d5f9e42418cf460a76d260d0b2f4eec2eb5855f043398edde85a83cab9b1cec',
	'site_url' => 'http://localhost/index.php',
);
