<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXReDAzg\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXReDAzg/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerXReDAzg.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerXReDAzg\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerXReDAzg\appAppKernelProdContainer([
    'container.build_hash' => 'XReDAzg',
    'container.build_id' => '3aee32f8',
    'container.build_time' => 1704491969,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXReDAzg');
