<?php

use Twig\Environment;
use Twig\Error\LoaderError;
use Twig\Error\RuntimeError;
use Twig\Extension\SandboxExtension;
use Twig\Markup;
use Twig\Sandbox\SecurityError;
use Twig\Sandbox\SecurityNotAllowedTagError;
use Twig\Sandbox\SecurityNotAllowedFilterError;
use Twig\Sandbox\SecurityNotAllowedFunctionError;
use Twig\Source;
use Twig\Template;

/* @bundles/CategoryBundle/Translations/en_US/messages.ini */
class __TwigTemplate_e9ea264d663e1102b055532239dcaa9704f882bc059c7a7ff4abfc3e828d0e79 extends Template
{
    private $source;
    private $macros = [];

    public function __construct(Environment $env)
    {
        parent::__construct($env);

        $this->source = $this->getSourceContext();

        $this->parent = false;

        $this->blocks = [
        ];
    }

    protected function doDisplay(array $context, array $blocks = [])
    {
        $macros = $this->macros;
        // line 1
        echo "mautic.category.createnew=\"Create new category...\"
mautic.category.form.alias.help=\"Alphanumeric string (hyphens allowed) used for URL generation of this category. A unique alias based on the title will be autogenerated if left empty.\"
mautic.category.form.confirmbatchdelete=\"Delete the selected categories? Associated items will NOT be deleted but will be assigned as uncategorized.\"
mautic.category.form.confirmdelete=\"Delete the category, %name%? Associated items will NOT be deleted but will be assigned as uncategorized.\"
mautic.category.global=\"Global\"
mautic.category.header.edit=\"Edit %type% Category - %name%\"
mautic.category.header.index=\"Categories\"
mautic.category.header.new=\"New Category\"
mautic.category.help.searchcommands=\"<strong>Search commands</strong><br />ids:ID1,ID2 (comma separated IDs, no spaces)<br />is:published<br />is:unpublished\"
mautic.category.menu.index=\"Categories\"
mautic.category.noresults.tip=\"Categories help organize and group items together. In many of the filters, you can type category:{alias} (replace {alias} with the real deal) to show the items within a specific category.\"
mautic.category.permissions.categories=\"Categories - User has access to\"
mautic.category.permissions.header=\"Category Permissions\"
mautic.global.global=\"Global\"";
    }

    /**
     * @codeCoverageIgnore
     */
    public function getTemplateName()
    {
        return "@bundles/CategoryBundle/Translations/en_US/messages.ini";
    }

    /**
     * @codeCoverageIgnore
     */
    public function getDebugInfo()
    {
        return array (  37 => 1,);
    }

    public function getSourceContext()
    {
        return new Source("", "@bundles/CategoryBundle/Translations/en_US/messages.ini", "/var/www/html/mautic/docroot/app/bundles/CategoryBundle/Translations/en_US/messages.ini");
    }
}
